### ISSUE TITLE
Add support for domain name in `-r` option

### ISSUE THREAD

**Issue by bricewge** [jschauma/spf#4]
On commit `8e4c1ec9e408e4c85b3d0fe9963d6d7a22ced74d`, with the Docker container or in Debian 11 proper, I get the following error when using the `-r` option with a domain name instead of an IP:
```
$ docker run 65ca5de4520b fsf.org -r ns1.gnu.org
Insecure dependency while running with -T switch at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 512.
$ docker run 65ca5de4520b fsf.org -r 198.27.68.225
fsf.org:
[...]
All others: softfail
```

Would it make sense to support passing  domain names at the same time as addresses?  At least having a error message informing that's not a valid IP address?

Thank you for that great tool, it's really handy to check SPF with this utility.

**Comment by jschauma** [comment]
Hey - just committed a fix for this, give it a spin and reopen this issue if there's a problem.  Thanks!
